"""
Whistleblower Export — Anonymized audit report with SHA-256 integrity hash.
Strips org identity, preserves all statistical findings.
"""
import hashlib
import json
from datetime import datetime


def anonymize_report(audit_result_dict, org_name=None):
    """
    Create anonymized report from audit results dict.

    Returns dict with org info stripped, stats preserved, SHA-256 hash added.
    """
    report = _deep_copy_dict(audit_result_dict)

    # Strip identifying info
    report.pop("org_id", None)
    report.pop("org_name", None)
    report.pop("audit_id", None)
    if org_name:
        report = _replace_in_dict(report, org_name, "Company A")

    # Add metadata
    report["_anonymization"] = {
        "anonymized": True,
        "generated_at": datetime.utcnow().isoformat(),
        "note": "This report was generated by VisionAI's automated fairness audit system. "
                "Organization identity has been anonymized per whistleblower protection principles.",
    }

    # Add integrity hash
    canonical = json.dumps(audit_result_dict, sort_keys=True, default=str)
    report["_integrity_hash"] = hashlib.sha256(canonical.encode()).hexdigest()

    return report


def _deep_copy_dict(obj):
    """Deep copy via JSON roundtrip."""
    return json.loads(json.dumps(obj, default=str))


def _replace_in_dict(obj, old, new):
    """Recursively replace string values."""
    if isinstance(obj, dict):
        return {k: _replace_in_dict(v, old, new) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [_replace_in_dict(i, old, new) for i in obj]
    elif isinstance(obj, str):
        return obj.replace(old, new)
    return obj
