from datetime import datetime
import hashlib
import json


def _build_audit_trail(audit: dict) -> list[dict]:
    pipeline_meta = audit.get("pipelineMeta", {})
    pipeline = audit.get("pipeline", {})

    audit_trail = []
    if pipeline_meta:
        for step, meta in pipeline_meta.items():
            audit_trail.append({
                "step": step,
                "status": meta.get("status", "unknown"),
                "updatedAt": meta.get("updatedAt"),
            })
    else:
        for step, status in pipeline.items():
            audit_trail.append({
                "step": step,
                "status": status,
                "updatedAt": None,
            })
    return sorted(
        audit_trail,
        key=lambda x: x.get("updatedAt") or "",
    )


def serialize_legal_export(audit_id: str, audit: dict) -> dict:
    regulations = audit.get("regulationMap", [])
    audit_trail = _build_audit_trail(audit)

    return {
        "auditId": audit_id,
        "generatedAt": datetime.utcnow().isoformat(),
        "disclaimer": (
            "This export contains compliance risk indicators based on statistical "
            "fairness analysis and does not constitute legal advice."
        ),
        "auditSummary": {
            "name": audit.get("name"),
            "domain": audit.get("domain"),
            "jurisdiction": audit.get("jurisdiction", "Global"),
            "status": audit.get("status"),
            "createdAt": audit.get("createdAt"),
            "fairnessScore": audit.get("fairnessScore"),
            "letterGrade": audit.get("letterGrade"),
            "protectedCols": audit.get("protectedCols", []),
            "labelCol": audit.get("labelCol"),
            "positiveLabel": audit.get("positiveLabel"),
        },
        "regulationMap": regulations,
        "auditTrail": audit_trail,
    }


def serialize_anonymized_export(audit_id: str, audit: dict) -> dict:
    canonical = json.dumps(audit, sort_keys=True, default=str)
    integrity_hash = hashlib.sha256(canonical.encode("utf-8")).hexdigest()

    data_bias = audit.get("dataBias", {})
    summarized_bias = []
    for attr, result in data_bias.items():
        metrics = result.get("metrics", {})
        summarized_bias.append({
            "attribute": attr,
            "severity": result.get("severity"),
            "disparateImpact": metrics.get("disparate_impact"),
            "statisticalParityDifference": metrics.get("statistical_parity_difference"),
            "explanation": result.get("explanation"),
        })

    return {
        "reportType": "AnonymizedWhistleblowerExport",
        "auditRef": audit_id,
        "generatedAt": datetime.utcnow().isoformat(),
        "integrityTokenSha256": integrity_hash,
        "note": (
            "This report was generated by VisionAI's automated fairness audit system. "
            "Organization identity has been anonymized per whistleblower protection principles."
        ),
        "anonymizedSummary": {
            "domain": audit.get("domain"),
            "jurisdiction": audit.get("jurisdiction", "Global"),
            "fairnessScore": audit.get("fairnessScore"),
            "letterGrade": audit.get("letterGrade"),
            "status": audit.get("status"),
            "createdAt": audit.get("createdAt"),
        },
        "riskIndicators": {
            "regulationMappings": audit.get("regulationMap", []),
            "dataBiasFindings": summarized_bias,
            "featureLaundering": audit.get("featureLaundering", []),
            "intersectionalFindings": audit.get("intersectional", []),
            "proxyWarnings": audit.get("proxies", []),
        },
        "auditTrail": _build_audit_trail(audit),
    }
